version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.9
  build:
    commands:
      - sam package --template-file template.yml --s3-bucket bucketname --output-template-file packaged-template.yml
artifacts:
  type: zip
  files:
    - '**/*'