version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.9
  pre_build:
    commands:
      - TIME=$(date +"%Y%m%d_%H%M%S")
      - ZIPFILE=myBuild_${TIME}.zip
  build:
    commands:
      - zip -r ${ZIPFILE} .
      - aws s3 cp ${ZIPFILE} s3://${S3_BUCKET}/${ZIPFILE}
      - aws cloudformation deploy --template-file template.yaml --stack-name my-new-stack --parameter-overrides CodeS3Bucket=${S3_BUCKET} CodeS3Key=${ZIPFILE} --capabilities CAPABILITY_NAMED_IAM
artifacts:
  type: zip
  files:
    - '**/*'