AWSTemplateFormatVersion: 2010-09-09
Description:

Parameters:
  ProjectName:
    Description: Project name
    Type: String
    Default: MyProject

  CodeS3Bucket:
    Description: The s3 Bucket name where the code is uploaded
    Type: String

  CodeS3Key:
    Description: The code zip file name in s3
    Type: String

Resources:

  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: HelloLambdaFunction
      Role: !GetAtt MyLambdaRole.Arn
      Runtime: python3.9
      Handler: lambda_function.lambda_handler
      Code:
        S3Bucket: !Ref CodeS3Bucket
        S3Key: !Ref CodeS3Key

  MyLambdaUrl:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      TargetFunctionArn:
        Fn::GetAtt:
          - MyLambdaFunction
          - Arn


  MyLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: MyLambdaRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
